[package]
name = "huff-ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codemap = "0.1.3"
ethers-rs = "0.2.3"
ethers-solc = "2.0.11"
eyre = "0.6.8"
serde_json = "1.0.108"
syn-solidity = "0.5.4"
